### PR TITLE
Build s390x-unknown-linux-musl target

### PR DESCRIPTION
**Pull request by messense**
bors: amd64 --target s390x-unknown-linux-musl

### CODE REVIEW

**Comment by messense** [comment]
bors try amd64 s390x-unknown-linux-musl

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors try amd64 --target s390x-unknown-linux-musl

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
```
  = note: /usr/local/musl/bin/../lib/gcc/s390x-unknown-linux-musl/9.2.0/../../../../s390x-unknown-linux-musl/bin/ld: /home/rust/src/target/s390x-unknown-linux-musl/debug/deps/libopenssl_sys-70172c64409e3e90.rlib(curve448.o): in function `recode_wnaf':
          /home/rust/src/target/s390x-unknown-linux-musl/debug/build/openssl-sys-1de3ca3326f5bf22/out/openssl-build/build/src/crypto/ec/curve448/curve448.c:575: undefined reference to `__ctzdi2'
          /usr/local/musl/bin/../lib/gcc/s390x-unknown-linux-musl/9.2.0/../../../../s390x-unknown-linux-musl/bin/ld: read-only segment has dynamic relocations
          collect2: error: ld returned 1 exit status
```

Hmm, not sure what's going on.

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors try arm64 armv7 --target s390x-unknown-linux-musl

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors try arm64 --target s390x-unknown-linux-musl

**Comment by paulwratt** [comment]
> Hmm, not sure what's going on.

I would check for an s390 patch for OpenSSL, or maybe if there is a version requirement (either for Rust or s390)

**Comment by messense** [comment]
`__ctzdi2` comes from [compiler-builtins](https://github.com/rust-lang/compiler-builtins/blob/83b2c07a6bfa394fa5979ca12b60536f402a792c/build.rs#L202), we're building a custom Rust std for s390x musl here since there is none from official release, probably need to check whether `compiler-builtins` was built properly.

**Comment by messense** [comment]
bors try amd64 s390x-unknown-linux-musl

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors try amd64 --target s390x-unknown-linux-musl

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors retry

**Comment by messense** [comment]
bors try armv7 --target s390x-unknown-linux-musl

**Comment by paulwratt** [comment]
I just checked that last conclusion, in the build script (number 2 of 3) the build docker sub-task has this at line 120. is it normal?

> #0 0.093 fatal: Not a valid object name af0c8329a3c6a17b5f2f0730899b9ecba2cf69ff^{commit}

https://github.com/messense/rust-musl-cross/actions/runs/3087155053/jobs/4992234259#step:8:122

**Comment by paulwratt** [comment]
ok, and I just checked which commit is was (and presumes rightly) it was the (last?) br-bot commit

**Comment by paulwratt** [comment]
also it seem someone invented "string format police" (the _other_ reason the log is so long).

**Pull request merged**
