### PR TITLE
Setup bors-ng

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
bors try amd64 --target aarch64-unknown-linux-musl

**Comment by messense** [comment]
bors try amd64 --target aarch64-unknown-linux-musl

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors try amd64 --target aarch64-unknown-linux-musl

**Comment by messense** [comment]
bors try-

**Comment by messense** [comment]
bors try amd64 arm64 --target aarch64-unknown-linux-musl x86_64-unknown-linux-musl

**Comment by paulwratt** [comment]
now I can see why you have been working so hard on the GH workflow so much recently - that is cool, great effort - I'm going to _star_ and keep the email that brought me here :)

**Comment by messense** [comment]
@paulwratt I learned about this fancy bors-ng usage in `cross`: https://github.com/cross-rs/cross/blob/ba030a63d539c07d27428ab470a2c8e47e01eb77/.github/workflows/ci.yml#L102-L213

They use bash to do the argument parsing, I merely changed it to use [actions/github-script](https://github.com/actions/github-script) which I think is much easier to grasp than bash.

**Pull request merged**
